### PR TITLE
Added function to convert hexadecimals to octal numbers

### PR DESCRIPTION
**Pull request by RotimiFreq**

### CODE REVIEW

**Comment by emmrys-jay** [comment]
Hi @RotimiFreq  It would have been nice if you created an issue before making your contributions. But someone will definitely review your PR and merge soon.

**Comment by emmrys-jay** [comment]
Also, have you joined our telegram community?

**Review by meshachdamilare — APPROVED** [review]

**Comment by meshachdamilare** [comment]
Your code works.
The PR has been merged, you can close this issue.

**Comment by RotimiFreq** [comment]
Okay, thank you. I would put that in mind .

**Comment by RotimiFreq** [comment]
I have joined the telegram group.

**Pull request merged**
