### PR TITLE
Refactored the code in hextoOct to hextoAny

### PR DESCRIPTION
**Pull request by RotimiFreq**

### CODE REVIEW

**Review by meshachdamilare — DISMISSED** [review]

**Review by emmrys-jay — APPROVED** [review]

**Comment by emmrys-jay** [comment]
I have resolved the conflicts

**Comment by Emmrys-Jay** [comment]
I have resolved the conflicts

**Comment by emmrys-jay** [comment]
@Christomesh

**Comment by emmrys-jay** [comment]
@RotimiFreq You made some mistakes with your variable naming within the function. 

For Example: using decnum and decNum interchangeably, hexdecNum and hexNum interchangeably.

**Comment by emmrys-jay** [comment]
I have fixed the mistakes already, and the function now works perfectly.

Also, update your fork after merging this PR for the other changes you would want to make.

**Comment by RotimiFreq** [comment]
Thanks for the correction.

**Pull request merged**
